const CHAT_MODEL = Symbol('CHAT_MODEL');
const ASR_CLIENT = Symbol('ASR_CLIENT');
const REDIS_CLIENT = Symbol('REDIS_CLIENT');
const MILVUS_CLIENT = Symbol('MILVUS_CLIENT');

export { CHAT_MODEL, ASR_CLIENT, REDIS_CLIENT, MILVUS_CLIENT };
